"use strict";
(function(module){if(typeof define==='function'&&define.amd){define(['exports'],function(exports){module(exports);});}else if(typeof exports==='object'&&exports!==null&&typeof exports.nodeName!=='string'){module(exports);}else{module(typeof self!=='undefined'?self:this);}}(function(B){let DA=2463534242,D7=()=>{let x=DA;x^=x<<13;x^=x>>>17;x^=x<<5;DA=x;return x;},V=f=>function(){return f(this);},Bk=f=>function(p1){return f(this,p1);},Dg=f=>function(p1,p2){return f(this,p1,p2);},DL=f=>(args,callback)=>{if(!args)
{args=[];}let javaArgs=Bp(Bh(),args.length);for(let i=0;i<args.length;++i){javaArgs.data[i]=O(args[i]);}E$(()=>{f.call(null,javaArgs);},callback);},Bd=target=>target.$clinit=()=>{},E_=obj=>{let cls=obj.constructor;let arrayDegree=0;while(cls[H]&&cls[H].item){++arrayDegree;cls=cls[H].item;}let clsName="";if(cls[H].primitiveKind!==0){clsName=cls[H].name;}else {clsName=cls[H]?cls[H].name||"a/"+cls.name:"@"+cls.name;}while(arrayDegree-->0){clsName+="[]";}return clsName;},E=superclass=>{if(superclass===0){return function()
{};}if(superclass===void 0){superclass=Bh();}return function(){superclass.call(this);};},H=Symbol("teavm_meta"),Q=cls=>{if(cls[H].classObject===null){cls[H].classObject=Ea(cls);}return cls[H].classObject;},Bh=()=>D,S=f=>function(){return f.apply(null,[this].concat(Array.prototype.slice.call(arguments)));},B8=source=>{return Object.assign({name:null,binaryName:null,parent:null,superinterfaces:[],modifiers:0,primitiveKind:0,itemType:null,arrayType:null,enclosingClass:null,declaringClass:null,simpleName:null,clinit
:()=>{},constructor:null,enumConstants:()=>null,resolvedEnumConstants:null,reflection:null,classObject:null,assignableCache:null,valueToObject:o=>o,objectToValue:o=>o},source||{});},Bo=(name,binaryName,kind,config)=>{let cls=()=>{};let meta=B8({name:name,binaryName:binaryName,modifiers:1|1<<4,primitiveKind:kind});cls[H]=meta;if(typeof config==='function'){config(meta);}return cls;},Co=Bo("char","C",4,meta=>{}),Et=Bo("int","I",5,meta=>{}),Fi=Bo("float","F",7,meta=>{}),D2=Bo("double","D",8,meta=>{}),DN=Bo("void",
"V",9),BG=(a,b)=>(a>>>0)/(b>>>0)>>>0,Fc=(a,b)=>(a>>>0)%(b>>>0)>>>0,BZ=(a,b)=>{a>>>=0;b>>>=0;return a<b? -1:a>b?1:0;},DB=BigInt(0),Dm=(lo,hi)=>BigInt.asIntN(64,BigInt.asUintN(64,BigInt(lo))|BigInt.asUintN(64,BigInt(hi)<<BigInt(32))),Fh=val=>BigInt.asIntN(64,BigInt(val|0)),DK=val=>BigInt.asIntN(64,BigInt(val>=0?Math.floor(val):Math.ceil(val))),Eb=(a,b)=>BigInt.asIntN(64,a+b),DJ=(a,b)=>BigInt.asIntN(64,a&b),ER=(a,b)=>BigInt.asIntN(64,a^b),Bp=(cls,sz)=>{let data=new Array(sz);data.fill(null);return new (BN(cls))(data);},Bu
=sz=>new Ej(new Uint16Array(sz)),BN=cls=>{let result=cls[H].arrayType;if(result===null){function JavaArray(data){(Bh()).call(this);this.data=data;}JavaArray.prototype=Object.create((Bh()).prototype);JavaArray.prototype.type=cls;JavaArray.prototype.constructor=JavaArray;JavaArray.prototype.toString=function(){let str="[";for(let i=0;i<this.data.length;++i){if(i>0){str+=", ";}str+=this.data[i].toString();}str+="]";return str;};JavaArray.prototype.cH=function(){let dataCopy;if('slice' in this.data){dataCopy=this.data.slice();}
else {dataCopy=new this.data.constructor(this.data.length);for(let i=0;i<dataCopy.length;++i){dataCopy[i]=this.data[i];}}return new (BN(this.type))(dataCopy);};let name="["+cls[H].binaryName;JavaArray[H]=B8({name:name,binaryName:name,parent:Bh(),itemType:cls});result=JavaArray;cls[H].arrayType=JavaArray;}return result;};
function Ft(array){return array.data.length;}
let BR,Ed=strings=>{Ey();BR=new Array(strings.length);for(let i=0;i<strings.length;++i){BR[i]=CJ(O(strings[i]));}},F=index=>BR[index],Ds=(array,offset,count)=>{let result="";let limit=offset+count;for(let i=offset;i<limit;i=i+1024|0){let next=Math.min(limit,i+1024|0);result+=String.fromCharCode.apply(null,array.subarray(i,next));}return result;},O=str=>str===null?null:DZ(str),Be=str=>str===null?null:str.bn,Ey=()=>Bm(),CJ;
{CJ=str=>str;}let I=ex=>{throw Ez(ex);},Bi=Symbol("javaException"),Ez=ex=>{if(!ex.$jsException){Dc(ex);}return ex.$jsException;},Dc=ex=>{let javaCause=Fl(ex);let jsCause=javaCause!==null?javaCause.$jsException:void 0;let cause=typeof jsCause==="object"?{cause:jsCause}:void 0;let err=new U("Java exception thrown",cause);if(typeof Error.captureStackTrace==="function"){Error.captureStackTrace(err);}err[Bi]=ex;ex.$jsException=err;Dl(err,ex);},Dl=(err,ex)=>{if(typeof DW==="function"&&err.stack){let stack=DW(err.stack);let javaStack
=Bp(D_(),stack.length);let elem;let noStack=false;for(let i=0;i<stack.length;++i){let element=stack[i];elem=Eh(O(element.className),O(element.methodName),O(element.fileName),element.lineNumber);if(elem==null){noStack=true;break;}javaStack.data[i]=elem;}if(!noStack){Es(ex,javaStack);}}},U;
if(typeof Reflect==='object'){let defaultMessage=Symbol("defaultMessage");U=function U(message,cause){let self=Reflect.construct(Error,[void 0,cause],U);Object.setPrototypeOf(self,U.prototype);self[defaultMessage]=message;return self;}
;U.prototype=Object.create(Error.prototype,{constructor:{configurable:true,writable:true,value:U},message:{get(){try {let javaException=this[Bi];if(typeof javaException==='object'){let javaMessage=DI(javaException);if(typeof javaMessage==="object"){return javaMessage!==null?javaMessage.toString():null;}}return this[defaultMessage];}catch(e){return "Exception occurred trying to extract Java exception message: "+e;}}}});}else {U=Error;}let DO=e=>e instanceof Error&&typeof e[Bi]==='object'?e[Bi]:null,C7=err=>{let ex
=err[Bi];if(!ex){ex=DT(O("(JavaScript) "+err.toString()));err[Bi]=ex;ex.$jsException=err;Dl(err,ex);}return ex;},DT=message=>E6(message),DI=t=>Ff(t),Fl=t=>Fn(t),D_=()=>Bh(),Eh=(className,methodName,fileName,lineNumber)=>{{return null;}},Es=(e,stack)=>{},El=outputFunction=>{let buffer="";return msg=>{let index=0;while(true){let next=msg.indexOf('\n',index);if(next<0){break;}outputFunction(buffer+msg.substring(index,next));buffer="";index=next+1;}buffer+=msg.substring(index);};},EA=typeof $rt_putStderrCustom===
"function"?$rt_putStderrCustom:typeof console==="object"?El(msg=>console.error(msg)):()=>{},CB=null,ED=data=>{let i=0;let packages=new Array(data.length);for(let j=0;j<data.length;++j){let prefixIndex=data[i++];let prefix=prefixIndex>=0?packages[prefixIndex]:"";packages[j]=prefix+data[i++]+".";}CB=packages;},Eg=[],BI=data=>{let packages=CB;let i=0;while(i<data.length){let cls=data[i++];Eg.push(cls);let m=B8();cls[H]=m;let className=data[i++];m.name=className!==0?className:null;if(m.name!==null){let packageIndex
=data[i++];if(packageIndex>=0){m.name=packages[packageIndex]+m.name;}}m.binaryName="L"+m.name+";";let superclass=data[i++];m.parent=superclass!==0?superclass:null;m.superinterfaces=data[i++];if(m.parent){cls.prototype=Object.create(m.parent.prototype);}else {cls.prototype={};}cls.prototype.constructor=cls;m.modifiers=data[i++];m.primitiveKind=0;let innerClassInfo=data[i++];if(innerClassInfo!==0){let enclosingClass=innerClassInfo[0];m.enclosingClass=enclosingClass!==0?enclosingClass:null;let declaringClass=innerClassInfo[1];m.declaringClass
=declaringClass!==0?declaringClass:null;let simpleName=innerClassInfo[2];m.simpleName=simpleName!==0?simpleName:null;}let clinit=data[i++];m.clinit=clinit!==0?()=>{m.clinit=()=>{};clinit();}:()=>{};let virtualMethods=data[i++];if(virtualMethods!==0){for(let j=0;j<virtualMethods.length;j+=2){let name=virtualMethods[j];let func=virtualMethods[j+1];if(typeof name==='string'){name=[name];}for(let k=0;k<name.length;++k){cls.prototype[name[k]]=func;}}}}},E$=(runner,callback)=>{let result;try {result=runner();}catch
(e){result=e;}if(typeof callback!=='undefined'){callback(result);}else if(result instanceof Error){throw result;}};
function D(){this.$id$=0;}
let Cw=a=>{return Q(E1(a));},E1=a=>{return a.constructor;},Eo=a=>{let b,c,d,e,f,g,h,i,j,k;b=a;if(!b.$id$)b.$id$=D7();c=a.$id$;Cj();if(!c)d=F(0);else{if(!c)e=32;else{f=0;e=c>>>16|0;if(e)f=16;else e=c;g=e>>>8|0;if(!g)g=e;else f=f|8;h=g>>>4|0;if(!h)h=g;else f=f|4;e=h>>>2|0;if(!e)e=h;else f=f|2;if(e>>>1|0)f=f|1;e=(32-f|0)-1|0;}i=(((32-e|0)+4|0)-1|0)/4|0;j=Bu(i);k=j.data;i=(i-1|0)*4|0;e=0;while(i>=0){h=e+1|0;k[e]=B9((c>>>i|0)&15,16);i=i-4|0;e=h;}d=DS(j);}b=T();J(J(b,F(1)),d);return Y(b);},Bs=E(0),Z=E(0),BM=E(0),M
=E(),DM=null,Ek=null,D$=null,Bm=()=>{Bm=Bd(M);E8();},EG=(a,b)=>{Bm();a.bn=Ds(b.data,0,b.data.length);},DS=a=>{let b=new M();EG(b,a);return b;},E5=(a,b)=>{a.bn=b;},DZ=a=>{let b=new M();E5(b,a);return b;},DG=(a,b)=>{let c;if(a===b)return 1;if(!(b instanceof M))return 0;c=b;return a.bn!==c.bn?0:1;},E8=()=>{let b;DM=Bu(0);b=new M;Bm();b.bn="";Ek=b;D$=new DD;},Bc=E(),CK=E(Bc),Ef=null,Cj=()=>{Cj=Bd(CK);D6();},D6=()=>{Ef=Q(Et);};
function Cc(){let a=this;D.call(a);a.bl=null;a.bp=0;}
let Ca=(a,b,c)=>{let d,e,f,g;d=a.bp;e=d-b|0;d=(d+c|0)-b|0;Dp(a,d);f=e-1|0;while(f>=0){g=a.bl.data;g[c+f|0]=g[b+f|0];f=f+(-1)|0;}a.bp=a.bp+(c-b|0)|0;},Ci=E(0),CC=E(Cc),En=a=>{a.bl=Bu(16);},T=()=>{let a=new CC();En(a);return a;},J=(a,b)=>{let c,d,e,f,g,h,i;c=a.bp;d=a;b=b===null?F(2):b;e=d;if(c>=0&&c<=e.bp){a:{b:{if(b===null)b=F(2);else if(b.bn.length?0:1)break b;f=e.bp+b.bn.length|0;Dp(e,f);g=e.bp-1|0;while(g>=c){e.bl.data[g+b.bn.length|0]=e.bl.data[g];g=g+(-1)|0;}e.bp=e.bp+b.bn.length|0;f=0;while(f<b.bn.length)
{h=e.bl;i=c+1|0;if(f<0)break a;if(f>=b.bn.length)break a;h.data[c]=b.bn.charCodeAt(f);f=f+1|0;c=i;}}return a;}I(EN());}b=new BV;CX(b);I(b);},B4=(a,b)=>{let c,d,e,f,g,h,i,j;c=a.bp;d=1;if(b<0){d=0;b= -b|0;}a:{if(BZ(b,10)<0){if(d)Ca(a,c,c+1|0);else{Ca(a,c,c+2|0);e=a.bl.data;f=c+1|0;e[c]=45;c=f;}a.bl.data[c]=B9(b,10);}else{g=1;h=1;f=BG((-1),10);b:{while(true){i=g*10|0;if(BZ(i,b)>0){i=g;break b;}h=h+1|0;if(BZ(i,f)>0)break;g=i;}}if(!d)h=h+1|0;Ca(a,c,c+h|0);if(d)f=c;else{e=a.bl.data;f=c+1|0;e[c]=45;}while(true){if
(!i)break a;e=a.bl.data;j=f+1|0;e[f]=B9(BG(b,i),10);b=Fc(b,i);i=BG(i,10);f=j;}}}return a;},Y=a=>{let b,c,d,e,f;b=new M;c=a.bl;d=c.data;e=a.bp;Bm();f=d.length;if(e>=0&&e<=(f-0|0)){b.bn=Ds(c.data,0,e);return b;}b=new Bq;Ba(b);I(b);},Dp=(a,b)=>{let c,d,e,f;c=a.bl.data.length;if(c<b){b=c>=1073741823?2147483647:CD(b,CD(c*2|0,5));d=a.bl.data;e=Bu(b);f=e.data;b=Dd(b,d.length);c=0;while(c<b){f[c]=d[c];c=c+1|0;}a.bl=e;}};
function Br(){let a=this;D.call(a);a.cj=null;a.cz=null;a.bP=0;a.cm=0;a.b4=null;}
let Fs=a=>{return a;},Dj=a=>{Dc(a);},Ff=a=>{return a.cj;},Fn=a=>{let b;b=a.cz;if(b===a)b=null;return b;},BY=E(Br),G=E(BY),Ba=a=>{Dj(a);a.bP=1;a.cm=1;},Fr=()=>{let a=new G();Ba(a);return a;},L=(a,b)=>{Dj(a);a.bP=1;a.cm=1;a.cj=b;},E6=a=>{let b=new G();L(b,a);return b;},Bn=E(),EQ=E(Bn),D4=(a,b)=>{switch(a.primitiveKind){default:return Bp(a,b);}},EC=E(Bn),CZ=E(0),Dy=E(0),CA=E(0);
function Db(){D.call(this);this.bM=null;}
let Ea=b=>{let c;c=new Db;c.bM=b;return c;},D0=a=>{let b;b=a.bM[H].itemType;return b===null?null:Q(b);},CG=E(),Bg=()=>{Bg=Bd(CG);EV();},Eu=b=>{let c,d,e,f,g;Bg();if(!((new URLSearchParams(location.search)).get('scene')==='arena'?1:0)){c=new DF;d=new By;e=new BX;f=new Cn;f.bF=1;f.ci=1.0;g=new C4;g.ck=c;f.b2=g;c.bT=f;c.bJ=6674943;c.br=d;c.cl=e;d=new Dx;d.b3=c;e=new Dw;e.co=c;Cy(c,d,e);return;}d=new CQ;c=new CE;e=new Cz;f=new BX;g=new C1;d.bX=Bp(B5,8);d.bs=24;d.bH=6674943;d.bz=F(3);d.bm=c;d.bt=e;d.b0=f;d.cE=g;c
=new Dv;c.cr=d;e=new Du;e.b_=d;Cy(d,c,e);},EY=(b,c,d)=>{valthorneHost.arenaHits=b;valthorneHost.arenaShots=c;valthorneHost.arenaAmmo=d;},EV=()=>{return;},Em=E(),E4=E(),R=(b,c)=>{if(b===null||b===undefined){return null;}let name='jso$functor$'+c;let result=b[name];if(typeof result!=='function'){let fn=function(){return b[c].apply(b,arguments);};result=()=>fn;b[name]=result;}return result();},Fe=E(),Cf=E(0);
function DF(){let a=this;D.call(a);a.br=null;a.cl=null;a.bu=0;a.bU=0;a.bT=null;a.bD=0.0;a.bJ=0;}
let EU=a=>{Cv(a);a.bT.bF=0;},Cv=a=>{let b,c;Df(a.br);Bf(a.br,0.0,(-0.5),0.0,12.0,0.5,12.0,5399671,0);BQ(a,F(4),(-5.0),0.0,(-3.0),1.7999999523162842);BQ(a,F(4),5.0,0.0,(-3.0),1.5);BQ(a,F(5),(-6.0),0.0,2.0,2.0);a.bu=0;a.bD=0.0;b=0;while(b<5){c=0;while(c<5){Cu(a.br,(c-2|0)*1.149999976158142,0.550000011920929+b*1.149999976158142,0.0,0.5,(c+b|0)%2|0?10005179:15381627,1);a.bu=a.bu+1|0;c=c+1|0;}b=b+1|0;}},BQ=(a,b,c,d,e,f)=>{let g,h;g=a.cl;h=new CV;h.ce=c;h.cd=d;h.cc=e;h.cq=f;h.cx=a;CL(g,b,h);},Fk=(a,b)=>{let c,d,e,
f;c=a.bT;if(!c.bF){d=c.cA;if(d!==null&&d.s(c))c.bF=1;else{e=c.bY+b;c.bY=e;if(e>=c.ci){c.b6=Eb(c.b6,Fh(1));c.bY=0.0;c=c.b2;if(c!==null){c=c.ck;c.bU=c.bU+1|0;}}}}e=a.bD+b*0.44999998807907104;f=0.0;Cd();if(!(e<f))f=!(e>100000.0)?e:100000.0;a.bD=f;Dn(a.br,b);},ET=a=>{let b,c,d,e;b=a.br;c=Bj(a.bD)*5.0;d=Bl(a.bD)*5.0;e=a.bJ;CH(b,c,5.0,d,e,90000.0);C5(a.br);},E2=a=>{Cp(a.br);},N=E(0),BP=E(0),Cu=(a,b,c,d,e,f,g)=>{Bf(a,b,c,d,e,e,e,f,g);},By=E(),Cp=a=>{globalThis.valthorneHost.close();},Df=a=>{globalThis.valthorneHost.clear();},CH
=(a,b,c,d,e,f)=>{globalThis.valthorneHost.light(b,c,d,e,f);},C5=a=>{globalThis.valthorneHost.render();},Dn=(a,b)=>{globalThis.valthorneHost.step(b);},Bf=(a,b,c,d,e,f,g,h,i)=>{let j;a:{if(!(isFinite(b)?1:0))break a;if(!(isFinite(c)?1:0))break a;if(!(isFinite(d)?1:0))break a;if(!(isFinite(e)?1:0))break a;if(!(isFinite(f)?1:0))break a;if(!(isFinite(g)?1:0))break a;if(e<=0.0)break a;if(f<=0.0)break a;if(!(g<=0.0)){globalThis.valthorneHost.box(b,c,d,e,f,g,h,!!i);return;}}j=new Bb;L(j,F(6));I(j);},Dh=E(0),BX=E(),CL
=(a,b,c)=>{let d,e,f;K(b);K(c);d=new Bz;d.b5=c;K(c);e=new BA;e.bZ=c;f=valthorneHost.assets.load(Be(b),R(W(d),"accept"),R(W(e),"accept"));b=new Ck;b.cu=f;return b;},B7=E(0);
function Dx(){D.call(this);this.b3=null;}
let DU=(a,b,c)=>{let d,e;d=a.b3;Bg();if(b&1){e=d.bu;if(e<80){Cu(d.br,Bj(e*2.4)*3.0,9.0,Bl(d.bu)*2.0,0.4000000059604645,d.bJ,1);d.bu=d.bu+1|0;}}if(b&2)Cv(d);d.bJ=c;},Ch=E(0);
function Dw(){D.call(this);this.co=null;}
let Fb=a=>{let b,c,d;b=a.co;Bg();c=b.bu;d=b.bU;globalThis.valthorneHost.report(c,d);},EJ=E(),Cy=(b,c,d)=>{let e,f,g,h,i,$$je;K(c);K(d);e=new CT;e.bw=K(b);if(!(isFinite(0.01666666753590107)?1:0)){c=new Bb;L(c,F(7));I(c);}e.bK=0.01666666753590107;e.bO=5;if(!e.bI&&!e.bA){a:{try{e.bw.D();}catch($$e){$$je=C7($$e);if($$je instanceof G){b=$$je;break a;}else if($$je instanceof BO){b=$$je;break a;}else{throw $$e;}}e.bI=1;b=new BB;b.ch=c;b.cg=e;b.cf=d;K(e);c=new BC;c.b$=e;globalThis.valthorneHost.connect(R(W(b),"run"),
R(W(c),"run"));return;}e.bA=1;b:{c:{try{e.bw.E();break b;}catch($$e){$$je=C7($$e);if($$je instanceof G){c=$$je;break c;}else if($$je instanceof BO){c=$$je;break c;}else{throw $$e;}}}if(b.bP){f=b.b4;g=f.data;h=g.length;i=h+1|0;d=D0(Cw(f));if(d===null){b=new BL;Ba(b);I(b);}if(d===Q(DN)){b=new Bb;Ba(b);I(b);}if(i<0){b=new DE;Ba(b);I(b);}f=D4(d.bM,i);i=Dd(i,h);h=0;while(h<i){f.data[h]=g[h];h=h+1|0;}f=f;g=f.data;b.b4=f;g[g.length-1|0]=c;}}I(b);}c=new Bw;L(c,F(8));I(c);};
function CQ(){let a=this;D.call(a);a.bm=null;a.bt=null;a.b0=null;a.cE=null;a.bR=null;a.bS=null;a.bk=null;a.bX=null;a.bq=0.0;a.bx=0.0;a.bB=0.0;a.bv=0.0;a.bG=0.0;a.bs=0;a.bE=0;a.bC=0;a.bH=0;a.bz=null;}
let Ev=a=>{let b,c,d;CP(a);b=new Cq;b.bW=a;K(F(9));K(b);c=new B1;c.b9=b;K(b);d=new B0;d.cb=b;valthorneHost.media.load("ui/crosshair.png",!!0,R(W(c),"accept"),R(W(d),"accept"));b=new Cr;b.bQ=a;K(F(10));K(b);c=new BJ;c.cp=b;K(b);d=new BK;d.cn=b;valthorneHost.media.load("audio/impact.wav",!!1,R(W(c),"accept"),R(W(d),"accept"));},CP=a=>{let b,c,d,e,f,g;Df(a.bm);Bf(a.bm,0.0,(-0.5),0.0,12.0,0.5,12.0,5399671,0);Bf(a.bm,(-12.0),2.0,0.0,0.5,2.0,12.0,2701641,0);Bf(a.bm,12.0,2.0,0.0,0.5,2.0,12.0,2701641,0);Bf(a.bm,0.0,
2.0,(-12.0),12.0,2.0,0.5,2701641,0);Bf(a.bm,0.0,2.0,12.0,12.0,2.0,0.5,2701641,0);a.bk=Cl(a.bm,0.0,1.0,8.0,0.3400000035762787,0.8999999761581421,0.3400000035762787,10005179,1,1);b=0;while(true){c=a.bX.data;if(b>=c.length)break;d=a.bm;e=((b%4|0)-1.5)*3.0;f=(-2)-((b/4|0)*4|0)|0;c[b]=Cl(d,e,1.2000000476837158,f,0.550000011920929,1.0,0.550000011920929,15381627,1,0);b=b+1|0;}d=a.b0;g=new Cs;g.b1=a;CL(d,F(4),g);a.bG=0.0;a.bv=0.0;a.bB=0.0;a.bx=0.0;a.bq=0.0;a.bs=24;a.bC=0;a.bE=0;},Bt=(a,b)=>{return valthorneHost.platform.keyDown(Be(b))
?1:0;},Ec=(a,b)=>{let c,d,e,f,g,h,i,j,k;a.bG=a.bG+b;a.bB=BU(0.0,a.bB-b);a.bq=a.bq+valthorneHost.platform.takeLook(0)*0.002199999988079071;a.bx=BU((-1.4500000476837158),Fa(1.4500000476837158,a.bx-valthorneHost.platform.takeLook(1)*0.002199999988079071));c=(!Bt(a,F(11))?0:1)-(!Bt(a,F(12))?0:1)|0;d=(!Bt(a,F(13))?0:1)-(!Bt(a,F(14))?0:1)|0;e=EZ(c*c+d*d);f=!Bt(a,F(15))?4.400000095367432:7.199999809265137;if(e>0.0){e=f/e;c=c*e;d=d*e;}g=valthorneHost.bodyComponent(a.bk.bo,3);if(Dr(a.bt,F(16))){f=B_(a.bk);h=Bx(a.bk);i
=Ce(a.bk);j=a.bk;k=j===null?0:j.bo;if(valthorneHost.rayDistance(f,h,i,0.0,(-1.0),0.0,1.0199999809265137,k)>=0.0)g=5.0;}j=a.bk;e=Bj(a.bq)*c+Bl(a.bq)*d;f= -Bl(a.bq)*c+Bj(a.bq)*d;valthorneHost.changeBody(j.bo,0,e,g,f);if(Bx(a.bk)<(-10.0))valthorneHost.changeBody(a.bk.bo,2,0.0,2.0,8.0);if(Dr(a.bt,F(17))&&a.bs<24&&a.bv===0.0)a.bv=1.5;e=a.bv;if(e>0.0){e=BU(0.0,e-b);a.bv=e;if(e===0.0){a.bs=24;Da(a.bt,600.0,0.07999999821186066,0.10000000149011612,0.0);}}if((valthorneHost.platform.buttons.has(0)?1:0)&&a.bB===0.0&&a.bv
===0.0&&a.bs>0)Ep(a);Dn(a.bm,b);},Ep=a=>{let b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t;a.bB=0.11999999731779099;a.bs=a.bs-1|0;a.bC=a.bC+1|0;b=Bl(a.bx);c=Bj(a.bq)*b;d=Bj(a.bx);e= -Bl(a.bq)*b;f=B_(a.bk);g=Bx(a.bk)+0.6499999761581421;h=Ce(a.bk);i=a.bk;j=valthorneHost.castRay(f,g,h,c,d,e,65.0,i===null?0:i.bo);if(j===null)k=null;else{k=new Di;i=C_(j.id);b=j.distance;k.b7=i;k.b8=b;}i=a.bS;if(i===null)Da(a.bt,95.0,0.07999999821186066,0.1599999964237213,0.0);else valthorneHost.media.play(i.bN,0.20000000298023224,0.0)?1
:0;if(k===null)return;l=k.b8;m=f+c*l;n=g+d*l;o=h+e*l;b=m-c*0.07999999821186066;f=n-d*0.07999999821186066;o=o-e*0.07999999821186066;p=a.bH;valthorneHost.particles.burst(b,f,o,p,10,!!1,!!1);q=a.bX.data;p=q.length;r=0;a:{while(true){if(r>=p)break a;i=q[r];s=k.b7;i=i;if(i===s)t=1;else if(s!==null&&Cw(s)===Q(B3)){j=s;t=i.bo==j.bo?1:0;}else t=0;if(t)break;r=r+1|0;}b=c*30.0;c=d*30.0+3.0;d=e*30.0;valthorneHost.changeBody(i.bo,1,b,c,d);a.bE=a.bE+1|0;}a.bz=F(18);},EW=a=>{let b,c,d,e,f,g,h;valthorneHost.setCamera(B_(a.bk),
Bx(a.bk)+0.6499999761581421,Ce(a.bk),a.bq,a.bx,72.0);b=a.bm;c=a.bH;CH(b,0.0,5.0,(-3.0),c,90000.0);C5(a.bm);valthorneHost.platform.beginOverlay();b=a.bR;if(b!==null){d=(!!0?innerHeight:innerWidth)/2.0-12.0;e=(!!1?innerHeight:innerWidth)/2.0-12.0;valthorneHost.media.draw(b.bL,d,e,24.0,24.0,1.0);}valthorneHost.platform.rectangle(24.0,100.0,330.0,116.0,1055012,0.8500000238418579);b=a.bt;c=a.bs;f=!(a.bv>0.0)?F(19):F(20);g=T();J(J(B4(J(g,F(21)),c),F(22)),f);f=Y(g);B2(b,f,40.0,129.0,20.0,16777215);b=a.bt;h=a.bE;c=
a.bC;f=T();B4(J(B4(J(f,F(23)),h),F(24)),c);f=Y(f);B2(b,f,40.0,156.0,16.0,9362409);b=a.bt;f=a.bz;B2(b,f,40.0,187.0,12.0,16777215);},EI=a=>{let b;b=a.bR;if(b!==null)valthorneHost.media.release(b.bL);b=a.bS;if(b!==null)valthorneHost.media.release(b.bN);Cp(a.bm);},C0=E(0),CE=E(By),Cl=(a,b,c,d,e,f,g,h,i,j)=>{let k;a:{if(!(isFinite(b)?1:0))break a;if(!(isFinite(c)?1:0))break a;if(!(isFinite(d)?1:0))break a;if(!(isFinite(e)?1:0))break a;if(!(isFinite(f)?1:0))break a;if(!(isFinite(g)?1:0))break a;if(e<=0.0)break a;if
(f<=0.0)break a;if(!(g<=0.0))return C_(DP(b,c,d,e,f,g,h,!!i,!!j));}k=new Bb;L(k,F(25));I(k);},DP=(b,c,d,e,f,g,h,i,j)=>{return (valthorneHost.createBox(b,c,d,[e,f,g],h,i,j)).id;},C$=E(0),Cz=E(),Dr=(a,b)=>{return valthorneHost.platform.takeKeyPress(Be(b))?1:0;},Da=(a,b,c,d,e)=>{valthorneHost.platform.tone(b,c,d,e);},B2=(a,b,c,d,e,f)=>{Fd(Be(b),c,d,e,f);},Fd=(b,c,d,e,f)=>{valthorneHost.platform.text(b,c,d,e,f);},Dz=E(0),C1=E();
function Dv(){D.call(this);this.cr=null;}
let DX=(a,b,c)=>{let d;d=a.cr;Bg();if(b&2)CP(d);d.bH=c;};
function Du(){D.call(this);this.b_=null;}
let DQ=a=>{let b,c,d,e;b=a.b_;Bg();c=b.bG|0;globalThis.valthorneHost.report(9,c);c=b.bE;d=b.bC;e=b.bs;EY(c,d,e);},CN=E(0),DD=E(),BW=E(),Ee=null,Er=null,BS=()=>{BS=Bd(BW);EX();},B9=(b,c)=>{BS();if(c>=2&&c<=36&&b>=0&&b<c)return b<10?(48+b|0)&65535:((97+b|0)-10|0)&65535;return 0;},EX=()=>{Ee=Q(Co);Er=Bp(BW,128);};
function Cn(){let a=this;D.call(a);a.ci=0.0;a.bY=0.0;a.b6=DB;a.bF=0;a.b2=null;a.cA=null;}
let CI=E(0);
function C4(){D.call(this);this.ck=null;}
let EF=E(),K=b=>{if(b!==null)return b;b=new BL;L(b,F(19));I(b);};
function CT(){let a=this;D.call(a);a.bw=null;a.bK=0.0;a.bO=0;a.by=0.0;a.bI=0;a.bA=0;a.bV=0;}
let X=E(0),CS=E(0);
function BB(){let a=this;D.call(a);a.ch=null;a.cg=null;a.cf=null;}
let D8=(b,c,d,e)=>{let f,g,h,i;f=c;g=d;h=e;b=b;c=b.ch;d=b.cg;b=b.cf;c.Z(g,h);h=!(g&4)?0:1;if(d.bV!=h){d.bV=h;d.by=0.0;}if(d.bI&&!d.bA){if((isFinite(f)?1:0)&&!(f<0.0)){a:{if(!d.bV){d.by=d.by+Fg(f,d.bK*d.bO);g=0;while(true){f=d.by;i=d.bK;if(!(f>=i))break a;h=g+1|0;if(g>=d.bO)break a;d.bw.bb(i);d.by=d.by-d.bK;g=h;}}}d.bw.x();b.bc();return;}b=new Bb;L(b,F(26));I(b);}c=new Bw;L(c,F(27));I(c);},De=E(0);
function BC(){D.call(this);this.b$=null;}
let E9=b=>{b=b.b$;if(!b.bA){b.bA=1;if(b.bI)b.bw.E();}};
function Dq(){D.call(this);this.cv=null;}
let W=b=>{if(b===null)return null;return !(b instanceof Dq)?b:b.cv;},B5=E(0),Ew=E(G),CF=E(Bc),E7=null,Cx=()=>{Cx=Bd(CF);D5();},D5=()=>{E7=Q(Fi);},Bb=E(G),Bw=E(G),BO=E(Br),Bq=E(G),CX=a=>{Ba(a);},Fv=()=>{let a=new Bq();CX(a);return a;},BL=E(G),Fp=E(),EM=E(),DV=E(),Bj=b=>{return Math.sin(b);},Bl=b=>{return Math.cos(b);},EZ=b=>{return Math.sqrt(b);},E3=()=>{return Math.random();},Dd=(b,c)=>{if(b<c)c=b;return c;},CD=(b,c)=>{if(b>c)c=b;return c;},Fg=(b,c)=>{return Math.min(b,c);},Fa=(b,c)=>{return Math.min(b,c);},D9
=(b,c)=>{return Math.max(b,c);},BU=(b,c)=>{return D9(b,c);},DE=E(G),BF=E(0);
function Cq(){D.call(this);this.bW=null;}
function Cr(){D.call(this);this.bQ=null;}
let BE=E(0);
function Cs(){D.call(this);this.b1=null;}
let D3=(a,b)=>{C3(b,(-8.0),0.0,(-8.0),0.0,2.0);},E0=(a,b)=>{let c,d;if(!DG(b,F(28))){c=a.b1;d=T();J(J(d,F(29)),b);c.bz=Y(d);}};
function CV(){let a=this;D.call(a);a.ce=0.0;a.cd=0.0;a.cc=0.0;a.cq=0.0;a.cx=null;}
let Eq=(a,b)=>{let c,d,e,f;c=a.ce;d=a.cd;e=a.cc;f=a.cq;C3(b,c,d,e,0.0,f);},DR=(a,b)=>{let c,d,e;if(!DG(b,F(28))){if(BD===null){c=new CO;d=null;e=null;c.cC=d;c.ct=T();c.cD=Bu(32);c.cw=0;c.cB=e;BD=c;}e=BD;c=T();J(J(c,F(30)),b);b=Y(c);c=e;Dk(c,b);Dk(c,F(31));}},Cm=E(Bc),Fm=null,C9=()=>{C9=Bd(Cm);EP();},EP=()=>{Fm=Q(D2);},BT=E(0);
function B1(){D.call(this);this.b9=null;}
let Fo=(b,c)=>{let d;d=c;b=b.b9;c=new DH;c.bL=d;b=b;c=c;b.bW.bR=c;},B6=E(0);
function B0(){D.call(this);this.cb=null;}
let EL=(b,c)=>{let d;c=O(c);b=b.cb.bW;d=T();J(J(d,F(32)),c);b.bz=Y(d);},Bv=E(0);
function Ex(){D.call(this);this.cF=0;}
function BJ(){D.call(this);this.cp=null;}
let EK=(b,c)=>{let d;d=c;b=b.cp;c=new CU;c.bN=d;b=b;c=c;b.bQ.bS=c;};
function BK(){D.call(this);this.cn=null;}
let EE=(b,c)=>{let d;c=O(c);b=b.cn.bQ;d=T();J(J(d,F(33)),c);b.bz=Y(d);};
function D1(){D.call(this);this.cG=0;}
let P=E();
function B3(){P.call(this);this.bo=0;}
let ES=(a,b)=>{a.bo=b;},C_=a=>{let b=new B3();ES(b,a);return b;},B_=a=>{return valthorneHost.bodyComponent(a.bo,0);},Bx=a=>{return valthorneHost.bodyComponent(a.bo,1);},Ce=a=>{return valthorneHost.bodyComponent(a.bo,2);},Do=E(0);
function Bz(){D.call(this);this.b5=null;}
let Fq=(b,c)=>{let d;d=c;b=b.b5;c=new DC;c.ca=d;b.bh(c);},C2=E(0);
function BA(){D.call(this);this.bZ=null;}
let Ei=(b,c)=>{c=O(c);b.bZ.bi(c);};
function Ck(){D.call(this);this.cu=0;}
let Dt=E(),Fj=null,Cd=()=>{Cd=Bd(Dt);EO();},EO=()=>{let b;b=new C6;b.cy=DJ(ER(DK(E3()*2.81474976710656E14-1.0),Dm(3740067437, 5)),Dm(4294967295, 65535));Fj=b;};
function Di(){let a=this;P.call(a);a.b7=null;a.b8=0.0;}
let CW=E(0);
function C6(){D.call(this);this.cy=DB;}
let CM=E(0);
function DH(){P.call(this);this.bL=0;}
let Ct=E(0);
function CU(){P.call(this);this.bN=0;}
let CR=E(0);
function DC(){let a=this;D.call(a);a.ca=0;a.cs=0;}
let C3=(a,b,c,d,e,f)=>{let g;if(a.cs){g=new Bw;L(g,F(34));I(g);}if((isFinite(b)?1:0)&&(isFinite(c)?1:0)&&(isFinite(d)?1:0)&&(isFinite(e)?1:0)&&(isFinite(f)?1:0)&&!(f<=0.0)){valthorneHost.assets.transform(a.ca,b,c,d,e,f);return;}g=new Bb;L(g,F(35));I(g);},DY=E(),BD=null,C8=E(0),CY=E(0),BH=E();
function Cb(){BH.call(this);this.cC=null;}
function B$(){let a=this;Cb.call(a);a.cw=0;a.ct=null;a.cD=null;a.cB=null;}
let Cg=E(B$),CO=E(Cg),Dk=(a,b)=>{if(b===null)b=F(2);EA(Be(b));},BV=E(Bq),EB=a=>{Ba(a);},EN=()=>{let a=new BV();EB(a);return a;},EH=E();
ED([]);
BI([D,0,0,[],1,0,0,0,Bs,0,D,[],1537,0,0,0,Z,0,D,[],1537,0,0,0,BM,0,D,[],1537,0,0,0,M,0,D,[Bs,Z,BM],17,0,()=>Bm(),0,Bc,0,D,[Bs],1025,0,0,0,CK,0,Bc,[Z],1,0,()=>Cj(),0,Cc,0,D,[Bs,BM],0,0,0,0,Ci,0,D,[],1537,0,0,0,CC,0,Cc,[Ci],1,0,0,0,Br,0,D,[],1,0,0,0,BY,0,Br,[],1,0,0,0,G,0,BY,[],1,0,0,0,Bn,0,D,[],1025,0,0,0,EQ,0,Bn,[],17,0,0,0,EC,0,Bn,[],17,0,0,0,CZ,0,D,[],1537,0,0,0,Dy,0,D,[CZ],1537,0,0,0,CA,0,D,[],1537,0,0,0,Db,0,D,[Dy,CA],17,0,0,0,CG,0,D,[],17,0,()=>Bg(),0,Em,0,D,[],17,0,0,0,E4,0,D,[],17,0,0,0,Fe,0,D,[],17,
0,0,0,Cf,0,D,[],1537,0,0,0,DF,0,D,[Cf],17,0,0,["D",V(EU),"bb",Bk(Fk),"x",V(ET),"E",V(E2)],N,0,D,[],1537,0,0,0,BP,0,D,[N],1537,0,0,0,By,0,D,[BP],1,0,0,0,Dh,0,D,[],1537,0,0,0,BX,0,D,[Dh],17,0,0,0,B7,0,D,[],1537,0,0,0,Dx,0,D,[B7],1,0,0,["Z",Dg(DU)],Ch,0,D,[],1537,0,0,0,Dw,0,D,[Ch],1,0,0,["bc",V(Fb)],EJ,0,D,[],17,0,0,0,CQ,0,D,[Cf],17,0,0,["D",V(Ev),"bb",Bk(Ec),"x",V(EW),"E",V(EI)],C0,0,D,[BP],1537,0,0,0,CE,0,By,[C0],17,0,0,0,C$,0,D,[N],1537,0,0,0,Cz,0,D,[C$],17,0,0,0,Dz,0,D,[],1537,0,0,0,C1,0,D,[Dz],17,0,0,0,Dv,
0,D,[B7],1,0,0,["Z",Dg(DX)],Du,0,D,[Ch],1,0,0,["bc",V(DQ)],CN,0,D,[],1537,0,0,0,DD,0,D,[CN],1,0,0,0,BW,0,D,[Z],1,0,()=>BS(),0,Cn,0,D,[],1,0,0,0,CI,0,D,[],1537,0,0,0]);
BI([C4,0,D,[CI],1,0,0,0,EF,0,D,[],17,0,0,0,CT,0,D,[N],17,0,0,0,X,0,D,[],1537,0,0,0,CS,0,D,[X],1537,0,0,0,BB,0,D,[CS],1,0,0,0,De,0,D,[X],1537,0,0,0,BC,0,D,[De],1,0,0,0,Dq,0,D,[],17,0,0,0,B5,0,D,[N],1537,0,0,0,Ew,0,G,[],1,0,0,0,CF,0,Bc,[Z],1,0,()=>Cx(),0,Bb,0,G,[],1,0,0,0,Bw,0,G,[],1,0,0,0,BO,0,Br,[],1,0,0,0,Bq,0,G,[],1,0,0,0,BL,0,G,[],1,0,0,0,Fp,0,D,[],1,0,0,0,EM,0,D,[],17,0,0,0,DV,0,D,[],17,0,0,0,DE,0,G,[],1,0,0,0,BF,0,D,[],1537,0,0,0,Cq,0,D,[BF],0,0,0,0,Cr,0,D,[BF],0,0,0,0,BE,0,D,[],1537,0,0,0,Cs,0,D,[BE],
0,0,0,["bh",Bk(D3),"bi",Bk(E0)],CV,0,D,[BE],0,0,0,["bh",Bk(Eq),"bi",Bk(DR)],Cm,0,Bc,[Z],1,0,()=>C9(),0,BT,0,D,[X],1536,0,0,0,B1,0,D,[BT],1,0,0,0,B6,0,D,[X],1536,0,0,0,B0,0,D,[B6],1,0,0,0,Bv,0,D,[],1537,0,0,0,Ex,0,D,[Bv],1,0,0,0,BJ,0,D,[BT],1,0,0,0,BK,0,D,[B6],1,0,0,0,D1,0,D,[Bv],1,0,0,0,P,0,D,[],1025,0,0,0,B3,0,P,[B5],16,0,0,0,Do,0,D,[X],1537,0,0,0,Bz,0,D,[Do],1,0,0,0,C2,0,D,[X],1537,0,0,0,BA,0,D,[C2],1,0,0,0,Ck,0,D,[Bv],1,0,0,0,Dt,0,D,[],17,0,()=>Cd(),0,Di,0,P,[],17,0,0,0,CW,0,D,[],1537,0,0,0,C6,0,D,[CW,Bs],
1,0,0,0,CM,0,D,[N],1537,0,0,0,DH,0,P,[CM],16,0,0,0]);
BI([Ct,0,D,[N],1537,0,0,0,CU,0,P,[Ct],16,0,0,0,CR,0,D,[N],1537,0,0,0,DC,0,D,[CR],16,0,0,0,DY,0,D,[],17,0,0,0,C8,0,D,[N],1537,0,0,0,CY,0,D,[],1537,0,0,0,BH,0,D,[C8,CY],1025,0,0,0,Cb,0,BH,[],1,0,0,0,B$,0,Cb,[Ci],1,0,0,0,Cg,0,B$,[],1025,0,0,0,CO,0,Cg,[],1,0,0,0,BV,0,Bq,[],1,0,0,0,EH,0,D,[Z],1025,0,0,0]);
let Ej=BN(Co);
Ed(["0","<java_object>@","null","Click Enter arena, then WASD / mouse / Space / R","models/tree.glb","models/tent.glb","Finite positions and positive finite extents required","Positive finite step and step limit required","Loop already started or closed","ui/crosshair.png","audio/impact.wav","KeyW","KeyS","KeyD","KeyA","ShiftLeft","Space","KeyR","Jolt impact / illuminated particles","","   RELOADING","AMMO "," / 24","Hits ","  Shots ","Invalid rigid box","Invalid frame delta","Loop is not running","cancelled",
"Tree load: ","Model load failed: ","\n","Crosshair: ","Sound: ","Model is closed","Finite transform and positive scale required"]);
M.prototype.toString=function(){return Be(this);};
M.prototype.valueOf=M.prototype.toString;D.prototype.toString=function(){return Be(Eo(this));};
D.prototype.__teavm_class__=function(){return E_(this);};
let C=DL(Eu);
C.javaException=DO;
let Fu=Symbol('jsoClass');
(()=>{let c;c=BB.prototype;c.run=S(D8);c=BC.prototype;c.run=S(E9);c=B1.prototype;c.accept=S(Fo);c=B0.prototype;c.accept=S(EL);c=BJ.prototype;c.accept=S(EK);c=BK.prototype;c.accept=S(EE);c=Bz.prototype;c.accept=S(Fq);c=BA.prototype;c.accept=S(Ei);})();
B.main=C;}));

//# sourceMappingURL=valthorne.js.map