package com.example;

/** Displayed fragments; prerequisites describe the surrounding application state. */
final class FeatureExamples {
    record Example(String title, String note, String code) {}
    private static Example example(String title, String note, String code) {
        return new Example(title, note, code);
    }
    static Example[] forPage(int page) {
        return switch(page) {
            case 0 -> new Example[]{
                example("Reuse geometry", "Initialization. scene is your Scene3D.\nCreate geometry once and share it across instances.", "var mesh = ModelBuilder3D.box(1, 1, 1);\nfor (int i = 0; i < 8; i++) {\n    var instance = new ModelInstance3D()\n        .setModel(mesh)\n        .setMaterial(new Material3D())\n        .setPosition(i * 2, 0, 0);\n    scene.add(instance);\n}"),
                example("Tune a material", "Initialization. Assign this material to a model.\nRoughness controls the surface response to light.", "var metal = new Material3D()\n    .setTint(new Color(0xFFB9A4DE))\n    .setMetallic(0.85f)\n    .setRoughness(0.25f);\nobject.setMaterial(metal);"),
                example("Animate a transform", "Update callback. object is an existing instance.\nAccumulate elapsed time in a float field named time.", "time += delta;\nobject.setPosition(0, 0, 1 + (float)Math.sin(time));\nobject.setRotation(0, 0, time * 0.4f);\nobject.setScale(1, 1, 1);"),
                example("Remove an instance", "Gameplay cleanup. Removing a model from a scene\ndoes not mean its shared assets should be destroyed.", "boolean removed = scene.remove(object);\nint remaining = scene.size();\nSystem.out.println(\"Removed: \" + removed);\nSystem.out.println(\"Scene objects: \" + remaining);"),
                example("Build a primitive floor", "Initialization. A shallow box gives the scene a visible\nground plane while remaining useful for simple prototypes.", "var floor = new ModelInstance3D()\n    .setModel(ModelBuilder3D.box(20, 20, 0.2f))\n    .setMaterial(new Material3D().setRoughness(0.9f))\n    .setPosition(0, 0, -0.1f);\nscene.add(floor);"),
                example("Create a repeated prop row", "Initialization. Reuse one model and material for all\ninstances; only each instance's transform is unique.", "var crateModel = ModelBuilder3D.box(1, 1, 1);\nvar crateMaterial = new Material3D().setRoughness(0.75f);\nfor (int i = 0; i < 12; i++) {\n    scene.add(new ModelInstance3D()\n        .setModel(crateModel)\n        .setMaterial(crateMaterial)\n        .setPosition(i * 1.5f, 0, 0.5f));\n}"),
                example("Change an instance at runtime", "Gameplay event. Mutate the existing instance instead\nof removing and reconstructing it when state changes.", "object.setPosition(4, -2, 1);\nobject.setRotation(0, 0, 1.57f);\nobject.setScale(1.5f, 1.5f, 1.5f);"),
                example("Inspect scene population", "Diagnostics or editor UI. Scene size is useful for a\nlightweight object-count budget and lifecycle checks.", "int modelCount = scene.size();\nif (modelCount > 500) {\n    System.out.println(\"Review the scene object budget\");\n}")};
            case 1 -> new Example[]{
                example("Orbit a light", "Update callback. light is your PointLight3D.\nKeep time as a field, not a per-frame local variable.", "time += delta;\nlight.setPosition(\n    (float)Math.cos(time) * 3,\n    (float)Math.sin(time) * 3,\n    2);"),
                example("Pulse the intensity", "Update callback. Animate an existing light rather\nthan allocating another light every frame.", "time += delta;\nfloat pulse = 0.5f + 0.5f * (float)Math.sin(time * 2);\nlight.setIntensity(250 + pulse * 150);\nlight.setRange(8);"),
                example("Choose shadow participation", "Initialization. Decorative surfaces can receive\nillumination without casting shadows over the UI.", "var surface = new Material3D()\n    .setRoughness(1)\n    .setCastsShadow(false)\n    .setReceivesShadow(false);\nobject.setMaterial(surface);"),
                example("Configure a 2D light", "Initialization. Import lighting2d.PointLight2D.\nRegister this light with your 2D lighting setup.", "var torch = new PointLight2D()\n    .setPosition(320, 180)\n    .setRadius(240)\n    .setElevation(80)\n    .setIntensity(1.2f)\n    .setCastsShadows(true);"),
                example("Add a shadowed key light", "Initialization. A focused key establishes form. Keep its\nrange close to the playable area to limit lighting work.", "var key = new PointLight3D()\n    .setPosition(4, -5, 7)\n    .setIntensity(700)\n    .setRange(14)\n    .setCastsShadows(true);\nscene.addLight(key);"),
                example("Add an inexpensive fill", "Initialization. A non-shadowed fill softens the dark side\nof objects without requiring another shadow map.", "var fill = new PointLight3D()\n    .setPosition(-5, 2, 4)\n    .setIntensity(180)\n    .setRange(10)\n    .setCastsShadows(false);\nscene.addLight(fill);"),
                example("Move light with gameplay", "Update callback. Reposition the existing light from game\nstate so illumination follows an actor or moving prop.", "light.setPosition(x, 0, 2.5f);\nlight.setRange(9);\nlight.setIntensity(420);"),
                example("Disable unnecessary shadows", "Runtime quality control. Changing shadow participation\nis useful when a light becomes distant or decorative.", "light.setCastsShadows(false);\nobject.getMaterial()\n    .setCastsShadow(false)\n    .setReceivesShadow(true);")};
            case 2 -> new Example[]{
                example("Read held input", "Update callback. x and speed are float fields.\nUse delta for movement measured in units per second.", "if (Keyboard.isKeyDown(Keyboard.D)) {\n    x += speed * delta;\n}\nif (Keyboard.isKeyDown(Keyboard.A)) {\n    x -= speed * delta;\n}"),
                example("Update shared state", "Update callback. walk is an Animation, ui a UIRoot.\nBoth receive the same elapsed frame time.", "walk.update(delta);\nui.update(delta);\nfloat progress = walk.getProgress01();\n// Use progress to drive gameplay or UI state."),
                example("Separate rendering from logic", "Render callback. viewport and ui were created\nin init. Keep resource loading out of this callback.", "Window.clear(new Color(0xFF101018));\nviewport.apply();\n// Draw your world here.\nui.draw();"),
                example("Release owned UI resources", "Dispose callback. ui is a nullable application field.\nOnly dispose resources that this application owns.", "if (ui != null) {\n    ui.dispose();\n    ui = null;\n}"),
                example("Use frame-rate independent motion", "Update callback. Multiplying by delta keeps speed\nconsistent across fast and slow machines.", "float movementPerSecond = 6.0f;\nif (Keyboard.isKeyDown(Keyboard.W)) {\n    x += movementPerSecond * delta;\n}"),
                example("Guard one-time initialization", "Initialization pattern. Build long-lived state once,\nthen let update and render reuse it every frame.", "if (ui == null) {\n    ui = new UIRoot();\n}\nif (viewport == null) {\n    viewport = new FitViewport(1280, 720);\n}"),
                example("Handle a window resize", "Resize handling. Recompute projection policy after the\ndisplay changes rather than rebuilding application state.", "viewport.update(Window.getWidth(), Window.getHeight());\nfloat visibleWidth = viewport.getWorldWidth();\nfloat visibleHeight = viewport.getWorldHeight();"),
                example("Coordinate animation and input", "Update callback. Input changes state and animation\nadvances from the same elapsed time source.", "boolean moving = Keyboard.isKeyDown(Keyboard.D);\nif (moving) x += speed * delta;\nwalk.setSpeed(moving ? 1.0f : 0.5f);\nwalk.update(delta);")};
            case 3 -> new Example[]{
                example("Compose a column", "Initialization. Import ui.nodes.nano classes.\nAdd this container to your existing UIRoot.", "var column = new NanoContainer();\ncolumn.getLayout().column().gap(12).padding(20);\ncolumn.add(new NanoLabel(\"Inventory\").fontSize(24));\ncolumn.add(new NanoLabel(\"Choose an item\"));\nui.add(column);"),
                example("Connect a button", "Initialization. The action runs when activated.\nUpdate the existing status label from the callback.", "var status = new NanoLabel(\"Ready\");\nvar button = new NanoButton(\"Start\");\nbutton.action(node -> status.text(\"Running\"));\nui.add(status);\nui.add(button);"),
                example("Scroll a long list", "Initialization. Give the scroll panel a finite height\nso content can extend beyond its visible bounds.", "var list = new NanoContainer();\nlist.getLayout().column().gap(8);\nfor (int i = 1; i <= 20; i++) {\n    list.add(new NanoLabel(\"Item \" + i));\n}\nvar scroll = new NanoScrollPanel().horizontal(false);\nscroll.getLayout().width(300).height(240);\nscroll.setContent(list);\nui.add(scroll);"),
                example("Opt into selectable text", "Initialization. Selection is an explicit label option.\nA separate action can copy a complete source string.", "String message = \"First line\\nSecond line\";\nvar text = new NanoLabel(message).selectable(true);\nvar copy = new NanoButton(\"Copy\");\ncopy.action(node -> TextEditing.copyText(message));\nui.add(text);\nui.add(copy);"),
                example("Build an action row", "Initialization. A row groups related controls while gap and\npadding keep interaction targets visually distinct.", "var actions = new NanoContainer();\nactions.getLayout().row().gap(10).padding(12);\nactions.add(new NanoButton(\"Save\"));\nactions.add(new NanoButton(\"Cancel\"));\nui.add(actions);"),
                example("Update a label from state", "Update or event callback. Keep a label reference and\nchange its content instead of rebuilding the UI tree.", "var counter = new NanoLabel(\"Items: 0\");\nui.add(counter);\nint itemCount = 12;\ncounter.text(\"Items: \" + itemCount);"),
                example("Create a flexible panel", "Initialization. Flexible dimensions allow the panel to\nadapt while padding protects its readable content area.", "var panel = new NanoContainer();\npanel.getLayout().column().gap(16).padding(24);\npanel.add(new NanoLabel(\"Settings\").fontSize(28));\npanel.add(new NanoButton(\"Apply\"));\nui.add(panel);"),
                example("Copy formatted source", "Button callback. Preserve the original source string so\ncopying is independent of wrapping in the visible label.", "String source = \"player.play();\\nplayer.setVolume(0.8f);\";\nvar sourceView = new NanoLabel(source).selectable(true);\nvar copySource = new NanoButton(\"Copy source\");\ncopySource.action(node -> TextEditing.copyText(source));\nui.add(sourceView);\nui.add(copySource);")};
            case 4 -> new Example[]{
                example("Play an effect", "After audio initialization. data is loaded SoundData.\nKeep the player to control or clean up playback later.", "var player = new SoundPlayer(data);\nplayer.setVolume(0.7f);\nplayer.setPitch(1.0f);\nplayer.play();"),
                example("Loop regional ambience", "After audio initialization. data is loaded SoundData.\nThe fade smooths the edge of this circular region.", "var ambience = new SoundPlayer(data);\nambience.setLooping(true);\nambience.setArea(SoundArea.circle(0, 0, 30, 8));\nambience.setVolume(0.4f);\nambience.play();"),
                example("Control playback", "Gameplay actions. player is an existing SoundPlayer.\nInvoke these at the appropriate pause/resume events.", "player.pause();\n// When the pause menu closes:\nplayer.resume();\n// When this effect should end:\nplayer.stop();"),
                example("Sample a room boundary", "A standalone area calculation. Half extents describe\nthe room size; fade extends its transition region.", "var room = SoundArea.rectangle(10, 20, 8, 6, 3);\nfloat inside = room.gainAt(10, 20, 0);\nfloat outside = room.gainAt(100, 100, 0);\nSystem.out.println(inside);\nSystem.out.println(outside);"),
                example("Create spherical ambience", "Initialization. A sphere is useful for caves, machinery\nand other three-dimensional regions with a soft edge.", "var cave = SoundArea.sphere(0, 0, -4, 18, 5);\nfloat centerGain = cave.gainAt(0, 0, -4);\nfloat edgeGain = cave.gainAt(20, 0, -4);"),
                example("Vary an effect's character", "Before playback. Small pitch and volume changes help\nrepeated effects sound less mechanical without new assets.", "player.setPitch(0.94f);\nplayer.setVolume(0.82f);\nplayer.play();"),
                example("Fade regional sound manually", "Update callback. Sample the listener against an area\nand apply the resulting gain to a looping player.", "var zone = SoundArea.circle(0, 0, 24, 6);\nfloat gain = zone.gainAt(x, 0, 0);\nplayer.setVolume(gain * 0.5f);"),
                example("Stop a sound during cleanup", "Dispose callback. Stop players owned by the application\nso looping audio does not outlive its game state.", "if (player != null) {\n    player.stop();\n    player = null;\n}")};
            case 5 -> new Example[]{
                example("Create a static floor", "Initialization. world is an initialized PhysicsWorld3D.\nUse static bodies for scenery that does not move.", "var floor = world.createBody(new BodySettings3D(\n    CollisionShape3D.box(20, 20, 1),\n    MotionType3D.STATIC)\n    .setPosition(0, 0, -0.5f)\n    .setFriction(0.8f));"),
                example("Apply an impulse", "Gameplay event. body is a dynamic RigidBody3D.\nApply once per event, not every render frame.", "body.activate();\nbody.addImpulse(new Vector3f(0, 0, 5));\n// Or assign a precise linear velocity:\nbody.setLinearVelocity(2, 0, 0);"),
                example("Bind a visual model", "Initialization. body and object already exist.\nThe physics body can drive the model transform.", "body.bind(object);\n// Detach before reusing this model independently:\nbody.unbind();"),
                example("Reuse a position buffer", "Keep positionBuffer as a Vector3f field initialized\nonce. Read into it when sampling the body's state.", "body.getPosition(positionBuffer);\nfloat altitude = positionBuffer.z;\nboolean moving = body.isActive();\n// Use altitude and moving in your gameplay logic."),
                example("Create a bouncing body", "Initialization. Restitution controls bounce while friction\ncontrols tangential resistance at contact surfaces.", "var ball = world.createBody(new BodySettings3D(\n    CollisionShape3D.sphere(0.5f),\n    MotionType3D.DYNAMIC)\n    .setPosition(0, 0, 6)\n    .setMass(1)\n    .setFriction(0.3f)\n    .setRestitution(0.75f));"),
                example("Wake a sleeping body", "Gameplay event. Activate before applying velocity or an\nimpulse to a body that may have gone to sleep.", "if (!body.isActive()) {\n    body.activate();\n}\nbody.setLinearVelocity(0, 4, 2);"),
                example("Read altitude without allocation", "Update callback. Reuse the same JOML vector for\nevery sample to avoid producing frame-loop garbage.", "body.getPosition(positionBuffer);\nif (positionBuffer.z < -20) {\n    body.setLinearVelocity(0, 0, 0);\n}"),
                example("Detach the rendered object", "Cleanup or pooling. Unbind before the model instance is\nrepurposed independently from its simulated body.", "body.unbind();\nobject.setPosition(0, 0, 0);\nobject.setRotation(0, 0, 0);")};
            case 6 -> new Example[]{
                example("Play a one-shot attack", "Initialization or attack start. frames contains your\nloaded AnimationFrame objects, not raw image files.", "var attack = new Animation(PlaybackMode.FORWARD, frames);\nattack.playOnce();\n// In update(float delta):\nattack.update(delta);\nif (attack.isFinished()) {\n    // Return your character to its idle state.\n}"),
                example("Reverse or ping-pong", "Configure an existing animation named walk.\nPlayback direction and repetition are independent.", "walk.setPlaybackMode(PlaybackMode.REVERSE);\nwalk.restart();\n// For a back-and-forth ambient animation instead:\nwalk.setPlaybackMode(PlaybackMode.BIDIRECTIONAL);\nwalk.setLooping(true);"),
                example("Seek and change speed", "Gameplay controls. time uses seconds, not frames.\nA frame index must be within the loaded frame range.", "walk.setSpeed(0.5f);\nwalk.time(0.25f);\nwalk.setFrame(0);\nwalk.pause();\n// Resume when the interaction finishes:\nwalk.play();"),
                example("Inspect playback progress", "Update callback. Use normalized progress for UI\nand the current frame index for diagnostics.", "float progress = walk.getProgress01();\nint currentFrame = walk.getCurrentIndex();\nint frameCount = walk.getFrameCount();\nint loops = walk.getLoopsCompleted();\n// Avoid printing these every frame in production."),
                example("Restart from the beginning", "Gameplay transition. Restart resets playback position\nand begins the animation again using its current mode.", "walk.restart();\nwalk.setSpeed(1.0f);\nwalk.setLooping(true);"),
                example("Play a finite sequence", "Gameplay event. Disable looping when an interaction should\nfinish once and hand control back to another state.", "walk.setLooping(false);\nwalk.setPlaybackMode(PlaybackMode.FORWARD);\nwalk.restart();"),
                example("Drive a progress display", "Update callback. Normalized progress is suitable for a\nbar, timeline or transition without knowing frame count.", "walk.update(delta);\nfloat normalized = walk.getProgress01();\nint percent = Math.round(normalized * 100);\n// Display percent in your HUD or editor."),
                example("Pause with the application", "Pause-menu event. Preserve the current frame while the\ngame is paused, then continue from that position.", "walk.pause();\n// Later, after leaving the pause menu:\nwalk.play();")};
            case 7 -> new Example[]{
                example("Choose fit or fill", "Initialization. Import valthorne.viewport classes.\nFit keeps the world visible; fill may crop the edges.", "var fit = new FitViewport(1280, 720);\nvar fill = new FillViewport(1280, 720);\nfit.update(Window.getWidth(), Window.getHeight());\nfill.update(Window.getWidth(), Window.getHeight());\n// Apply the policy chosen for this draw pass:\nfit.apply();"),
                example("Convert pointer coordinates", "Input/update callback. viewport has been updated\nfor the current window size before this conversion.", "var point = viewport.screenToWorld(Mouse.getX(), Mouse.getY());\nif (point != null) {\n    float worldX = point.x;\n    float worldY = point.y;\n    // Use these coordinates for world interaction.\n}"),
                example("Render a clipped region", "Render callback. Coordinates are in world units.\nThe helper restores the scissor after the callback.", "viewport.applyScissor(0, 0, 320, 180, () -> {\n    // Draw content restricted to this world rectangle.\n});"),
                example("Resize the logical world", "Resize/settings handler. Change the logical size\nthen recompute the viewport for the actual display.", "viewport.setWorldSize(1920, 1080);\nviewport.update(Window.getWidth(), Window.getHeight());\nfloat logicalWidth = viewport.getWorldWidth();\nfloat logicalHeight = viewport.getWorldHeight();"),
                example("Apply before drawing", "Render callback. Apply the viewport before its matching\nworld pass so projection and visible bounds agree.", "viewport.update(Window.getWidth(), Window.getHeight());\nviewport.apply();\n// Draw world-space content after apply()."),
                example("Use a fill viewport", "Initialization. Fill preserves aspect ratio while covering\nthe display, which can crop the outer world edges.", "var gameplay = new FillViewport(1280, 720);\ngameplay.update(Window.getWidth(), Window.getHeight());\ngameplay.apply();"),
                example("Use a fit viewport for UI", "Initialization. Fit keeps the complete logical canvas\nvisible and is useful when cropping would hide controls.", "var interfaceView = new FitViewport(1920, 1080);\ninterfaceView.update(Window.getWidth(), Window.getHeight());\ninterfaceView.apply();"),
                example("Inspect logical dimensions", "Resize or diagnostics. Read the effective world size\nafter updating the viewport for the current display.", "viewport.update(Window.getWidth(), Window.getHeight());\nfloat worldWidth = viewport.getWorldWidth();\nfloat worldHeight = viewport.getWorldHeight();\nSystem.out.println(worldWidth + \" x \" + worldHeight);")};
            default -> throw new IllegalArgumentException("Unknown feature page: " + page);
        };
    }
}
