package com.example;

/** Displayed fragments; prerequisites describe the surrounding application state. */
final class FeatureExamples {
    record Example(String title, String note, String code) {}
    private static Example example(String title, String note, String code) {
        return new Example(title, note, code);
    }
    static Example[] forPage(int page) {
        return switch(page) {
            case 0 -> new Example[]{
                example("Reuse geometry", "Initialization. scene is your Scene3D.\nCreate geometry once and share it across instances.", "var mesh = ModelBuilder3D.box(1, 1, 1);\nfor (int i = 0; i < 8; i++) {\n    var instance = new ModelInstance3D()\n        .setModel(mesh)\n        .setMaterial(new Material3D())\n        .setPosition(i * 2, 0, 0);\n    scene.add(instance);\n}"),
                example("Tune a material", "Initialization. Assign this material to a model.\nRoughness controls the surface response to light.", "var metal = new Material3D()\n    .setTint(new Color(0xFFB9A4DE))\n    .setMetallic(0.85f)\n    .setRoughness(0.25f);\nobject.setMaterial(metal);"),
                example("Animate a transform", "Update callback. object is an existing instance.\nAccumulate elapsed time in a float field named time.", "time += delta;\nobject.setPosition(0, 0, 1 + (float)Math.sin(time));\nobject.setRotation(0, 0, time * 0.4f);\nobject.setScale(1, 1, 1);"),
                example("Remove an instance", "Gameplay cleanup. Removing a model from a scene\ndoes not mean its shared assets should be destroyed.", "boolean removed = scene.remove(object);\nint remaining = scene.size();\nSystem.out.println(\"Removed: \" + removed);\nSystem.out.println(\"Scene objects: \" + remaining);")};
            case 1 -> new Example[]{
                example("Orbit a light", "Update callback. light is your PointLight3D.\nKeep time as a field, not a per-frame local variable.", "time += delta;\nlight.setPosition(\n    (float)Math.cos(time) * 3,\n    (float)Math.sin(time) * 3,\n    2);"),
                example("Pulse the intensity", "Update callback. Animate an existing light rather\nthan allocating another light every frame.", "time += delta;\nfloat pulse = 0.5f + 0.5f * (float)Math.sin(time * 2);\nlight.setIntensity(250 + pulse * 150);\nlight.setRange(8);"),
                example("Choose shadow participation", "Initialization. Decorative surfaces can receive\nillumination without casting shadows over the UI.", "var surface = new Material3D()\n    .setRoughness(1)\n    .setCastsShadow(false)\n    .setReceivesShadow(false);\nobject.setMaterial(surface);"),
                example("Configure a 2D light", "Initialization. Import lighting2d.PointLight2D.\nRegister this light with your 2D lighting setup.", "var torch = new PointLight2D()\n    .setPosition(320, 180)\n    .setRadius(240)\n    .setElevation(80)\n    .setIntensity(1.2f)\n    .setCastsShadows(true);")};
            case 2 -> new Example[]{
                example("Read held input", "Update callback. x and speed are float fields.\nUse delta for movement measured in units per second.", "if (Keyboard.isKeyDown(Keyboard.D)) {\n    x += speed * delta;\n}\nif (Keyboard.isKeyDown(Keyboard.A)) {\n    x -= speed * delta;\n}"),
                example("Update shared state", "Update callback. walk is an Animation, ui a UIRoot.\nBoth receive the same elapsed frame time.", "walk.update(delta);\nui.update(delta);\nfloat progress = walk.getProgress01();\n// Use progress to drive gameplay or UI state."),
                example("Separate rendering from logic", "Render callback. viewport and ui were created\nin init. Keep resource loading out of this callback.", "Window.clear(new Color(0xFF101018));\nviewport.apply();\n// Draw your world here.\nui.draw();"),
                example("Release owned UI resources", "Dispose callback. ui is a nullable application field.\nOnly dispose resources that this application owns.", "if (ui != null) {\n    ui.dispose();\n    ui = null;\n}")};
            case 3 -> new Example[]{
                example("Compose a column", "Initialization. Import ui.nodes.nano classes.\nAdd this container to your existing UIRoot.", "var column = new NanoContainer();\ncolumn.getLayout().column().gap(12).padding(20);\ncolumn.add(new NanoLabel(\"Inventory\").fontSize(24));\ncolumn.add(new NanoLabel(\"Choose an item\"));\nui.add(column);"),
                example("Connect a button", "Initialization. The action runs when activated.\nUpdate the existing status label from the callback.", "var status = new NanoLabel(\"Ready\");\nvar button = new NanoButton(\"Start\");\nbutton.action(node -> status.text(\"Running\"));\nui.add(status);\nui.add(button);"),
                example("Scroll a long list", "Initialization. Give the scroll panel a finite height\nso content can extend beyond its visible bounds.", "var list = new NanoContainer();\nlist.getLayout().column().gap(8);\nfor (int i = 1; i <= 20; i++) {\n    list.add(new NanoLabel(\"Item \" + i));\n}\nvar scroll = new NanoScrollPanel().horizontal(false);\nscroll.getLayout().width(300).height(240);\nscroll.setContent(list);\nui.add(scroll);"),
                example("Opt into selectable text", "Initialization. Selection is an explicit label option.\nA separate action can copy a complete source string.", "String message = \"First line\\nSecond line\";\nvar text = new NanoLabel(message).selectable(true);\nvar copy = new NanoButton(\"Copy\");\ncopy.action(node -> TextEditing.copyText(message));\nui.add(text);\nui.add(copy);")};
            case 4 -> new Example[]{
                example("Play an effect", "After audio initialization. data is loaded SoundData.\nKeep the player to control or clean up playback later.", "var player = new SoundPlayer(data);\nplayer.setVolume(0.7f);\nplayer.setPitch(1.0f);\nplayer.play();"),
                example("Loop regional ambience", "After audio initialization. data is loaded SoundData.\nThe fade smooths the edge of this circular region.", "var ambience = new SoundPlayer(data);\nambience.setLooping(true);\nambience.setArea(SoundArea.circle(0, 0, 30, 8));\nambience.setVolume(0.4f);\nambience.play();"),
                example("Control playback", "Gameplay actions. player is an existing SoundPlayer.\nInvoke these at the appropriate pause/resume events.", "player.pause();\n// When the pause menu closes:\nplayer.resume();\n// When this effect should end:\nplayer.stop();"),
                example("Sample a room boundary", "A standalone area calculation. Half extents describe\nthe room size; fade extends its transition region.", "var room = SoundArea.rectangle(10, 20, 8, 6, 3);\nfloat inside = room.gainAt(10, 20, 0);\nfloat outside = room.gainAt(100, 100, 0);\nSystem.out.println(inside);\nSystem.out.println(outside);")};
            case 5 -> new Example[]{
                example("Create a static floor", "Initialization. world is an initialized PhysicsWorld3D.\nUse static bodies for scenery that does not move.", "var floor = world.createBody(new BodySettings3D(\n    CollisionShape3D.box(20, 20, 1),\n    MotionType3D.STATIC)\n    .setPosition(0, 0, -0.5f)\n    .setFriction(0.8f));"),
                example("Apply an impulse", "Gameplay event. body is a dynamic RigidBody3D.\nApply once per event, not every render frame.", "body.activate();\nbody.addImpulse(new Vector3f(0, 0, 5));\n// Or assign a precise linear velocity:\nbody.setLinearVelocity(2, 0, 0);"),
                example("Bind a visual model", "Initialization. body and object already exist.\nThe physics body can drive the model transform.", "body.bind(object);\n// Detach before reusing this model independently:\nbody.unbind();"),
                example("Reuse a position buffer", "Keep positionBuffer as a Vector3f field initialized\nonce. Read into it when sampling the body's state.", "body.getPosition(positionBuffer);\nfloat altitude = positionBuffer.z;\nboolean moving = body.isActive();\n// Use altitude and moving in your gameplay logic.")};
            case 6 -> new Example[]{
                example("Play a one-shot attack", "Initialization or attack start. frames contains your\nloaded AnimationFrame objects, not raw image files.", "var attack = new Animation(PlaybackMode.FORWARD, frames);\nattack.playOnce();\n// In update(float delta):\nattack.update(delta);\nif (attack.isFinished()) {\n    // Return your character to its idle state.\n}"),
                example("Reverse or ping-pong", "Configure an existing animation named walk.\nPlayback direction and repetition are independent.", "walk.setPlaybackMode(PlaybackMode.REVERSE);\nwalk.restart();\n// For a back-and-forth ambient animation instead:\nwalk.setPlaybackMode(PlaybackMode.BIDIRECTIONAL);\nwalk.setLooping(true);"),
                example("Seek and change speed", "Gameplay controls. time uses seconds, not frames.\nA frame index must be within the loaded frame range.", "walk.setSpeed(0.5f);\nwalk.time(0.25f);\nwalk.setFrame(0);\nwalk.pause();\n// Resume when the interaction finishes:\nwalk.play();"),
                example("Inspect playback progress", "Update callback. Use normalized progress for UI\nand the current frame index for diagnostics.", "float progress = walk.getProgress01();\nint currentFrame = walk.getCurrentIndex();\nint frameCount = walk.getFrameCount();\nint loops = walk.getLoopsCompleted();\n// Avoid printing these every frame in production.")};
            case 7 -> new Example[]{
                example("Choose fit or fill", "Initialization. Import valthorne.viewport classes.\nFit keeps the world visible; fill may crop the edges.", "var fit = new FitViewport(1280, 720);\nvar fill = new FillViewport(1280, 720);\nfit.update(Window.getWidth(), Window.getHeight());\nfill.update(Window.getWidth(), Window.getHeight());\n// Apply the policy chosen for this draw pass:\nfit.apply();"),
                example("Convert pointer coordinates", "Input/update callback. viewport has been updated\nfor the current window size before this conversion.", "var point = viewport.screenToWorld(Mouse.getX(), Mouse.getY());\nif (point != null) {\n    float worldX = point.x;\n    float worldY = point.y;\n    // Use these coordinates for world interaction.\n}"),
                example("Render a clipped region", "Render callback. Coordinates are in world units.\nThe helper restores the scissor after the callback.", "viewport.applyScissor(0, 0, 320, 180, () -> {\n    // Draw content restricted to this world rectangle.\n});"),
                example("Resize the logical world", "Resize/settings handler. Change the logical size\nthen recompute the viewport for the actual display.", "viewport.setWorldSize(1920, 1080);\nviewport.update(Window.getWidth(), Window.getHeight());\nfloat logicalWidth = viewport.getWorldWidth();\nfloat logicalHeight = viewport.getWorldHeight();")};
            default -> throw new IllegalArgumentException("Unknown feature page: " + page);
        };
    }
}
